FROM amsterdam/python:3.9-buster
MAINTAINER datapunt@amsterdam.nl

RUN apt-get update && apt-get -y --no-install-recommends install unixodbc-dev libgdal-dev

# Install gobbagextract in /app folder
WORKDIR /app

# Install required Python packages
COPY requirements.txt /app/
RUN LIBGDAL_VERSION=$(gdal-config --version) pip3 install --no-cache-dir -r requirements.txt
RUN rm requirements.txt

# Copy gobbagextract module
COPY gobbagextract gobbagextract

# Remove gobcore/gobconfig tests (if present)
RUN rm -rf /app/src/gobcore/tests
RUN rm -rf /app/src/gobconfig/tests

# Copy tests
COPY tests tests
COPY .flake8 .flake8
COPY test.sh test.sh

# Copy jenkins files
COPY .jenkins /.jenkins
